server:
  port: 8083

spring:
  config:
    import: "optional:configserver:http://10.0.16.245:8888/"
  cloud:
    config:
      name: notice-service
      profile: config

  main:
    allow-bean-definition-overriding: true